language: node_js
node_js:
- 4.0
before_install:
- npm install -g gulp-cli
install:
- npm install
after_success:
- chmod +x ./bin/create-release-tag.sh
- "./bin/create-release-tag.sh"
branches:
  except:
  - "/^v/"
deploy:
  provider: heroku
  app: lcc-whatson
  api_key:
    secure: D3m8WYmJorAPRulKPTbPtG2n2b1QoKAG23Tv4ywStYKCYqofMm1uo70Qr6ZOp6mxLzGtuu8T+tV+JLPyFcxWX50zHp8U3MtQKH8Lm0GfKNgcaSWI9Z3AoaM431HgXcA1oBLZPmq7p2RoYiT/9O8E20OH7pMefEd56WvXRuoPizPP+IAAQQEaxe18oyp2sR+NJ3aoRC/TF4Gm9oGXEGcwcc4SU/arlHsHqbuUwbm5pG42KfHsDHQ2Ef0Z5oyJ0EyGHgC6kcP/+N+uNZE1Je8aMBbPi0D7s2+xFG6GAg7/3PsZt0YWCaTCzncAD7AXmIt+pRRRFDYHaAPeq71yXQ7zdjK1yCFLN5h78tKn0nWH5Qg2JTbFenJMo7bt9x9P4f0zMYrWSC3LKfsBMfJtlSqCTKBcFJ9JVYCsaOALNmqmFcGrW7Vo9iLkaa8SbkwHRamGnaovBdpMqIRiOEK75wFGf+rp/ZGpT4wEDQqAn11cgsNrRYOXuseB5l89vRNBlZ5TECjMmGrT0Byqs6p9ccpqSx5dgFYAFwB9xZYmCfncMNtIM1nJCDAk0X3SEok5RScSQpvybF6uaPOky/WXv8StuelL3KHulMEcSIrXMxqNNZU6ULvUbhizkJFf0uoWESt33pxOFvCn8Dhf+8HPFHZ4QPlVatcvjgPn+ahZANrTqT4=
notifications:
  email: false
sudo: falsecomm